### ISSUE TITLE
Unexpected token {

### ISSUE THREAD

**Issue by pizzafox** [nodejs/repl#23]
Attempting to run

```bash
C:\Users\username>node-prototype-repl
```
On Windows 10 with Node.js `v8.12.0`, the latest Node.js LTS version (as of writing), results in this fatal error:
```js
C:\Users\username\AppData\Roaming\npm\node_modules\@nodejs\repl\src\repl.js:227
          } catch {} // eslint-disable-line no-empty
                  ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\username\AppData\Roaming\npm\node_modules\@nodejs\repl\src\index.js:7:14)
```

**Comment by devsnek** [comment]
At the moment this is being developed against Node.js nightly builds, as it is intended to eventually replace the repl built into node. If you want to open a pr and change it i would accept it but i can't guarantee the compatibility would stay as more code is added.

**Comment by devsnek** [comment]
node 8 is no longer lts
